chefforhire/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from . import views

from django.urls import path
from . import views

urlpatterns = [
  path('', views.landing, name='landing'),
  path('about/', views.about, name='about'),
  path('chefs/', views.ChefsIndex.as_view(), name='chefs'),
  path('chefs/<int:pk>/', views.chef_detail, name='chef_detail'),
  path('chefs/create', views.ChefsCreate.as_view(), name='chef_create'),
  path('chefs/<int:pk>/update', views.ChefsUpdate.as_view(), name='chef_update'),
  path('chefs/<int:pk>/delete', views.ChefsDelete.as_view(), name='chef_delete'),
  path('user/create/', views.UserCreate.as_view(), name='user_create'),
  path('user/<int:pk>/', views.user_detail, name='user_detail'),
  path('user/<int:pk>/update', views.UserUpdate.as_view(), name='user_update'),
  path('user/<int:pk>/delete', views.UserDelete.as_view(), name='user_delete'),
  path('chefs/<int:pk>/add_booking/', views.add_booking, name='add_booking'),
  path('chefs/<int:pk>/add_avatar/', views.add_avatar, name='add_avatar'),
  # path('chefs/<int:pk>/add_gallery/', views.add_gallery, name='add_gallery'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User



MEALS = (
    ('B', 'Breakfast'),
    ('R', 'Brunch'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Chef(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=12)
    email = models.EmailField(max_length=50)
    bio = models.TextField(max_length=500)
    location = models.CharField(max_length=100)
    hourly = models.IntegerField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('chef_detail', kwargs={'pk': self.id})

# the image for chef's profile
class Avatar(models.Model):
    url = models.CharField(max_length=200)
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for chef_id: {self.chef_id} @{self.url}'

class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    location = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)

    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'pk': self.id})

class Gallery(models.Model):
    url = models.CharField(max_length=200)
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for chef_id: {self.chef_id} @{self.url}'

class Booking(models.Model):
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE)
    host = models.CharField(max_length=30)
    occassion = models.CharField(max_length=100)
    date = models.DateField('Date')
    attendees = models.IntegerField()
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
   

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'

    class Meta:
        ordering = ('-date',)

main_app/forms.py
from django.forms import ModelForm
from .models import Booking


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        fields = (
            'host',
            'occassion',
            'date',
            'attendees',
            'meal',
        )

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
# from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Chef, User, Avatar, Gallery
from .forms import BookingForm

import boto3
import uuid

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'dogcollector-photo-uploads'


# Create your views here.
def landing(request):
  return render(request, 'landing.html')

def about(request):
  return render(request, 'about.html')

# Chefs class
class ChefsIndex(ListView):
  model = Chef
  template_name = 'chefs/index.html'

# class ChefsDetail(DetailView):
#   model = Chef
#   template_name = 'chefs/detail.html'

def chef_detail(request, pk):
  chef = Chef.objects.get(id=pk)
  avatar = Avatar.objects.filter(chef_id=pk)
  booking_form = BookingForm()
  print(avatar)
  return render(request, 'chefs/detail.html', { 
    'chef': chef,
    'booking_form': booking_form,
    'avatar': avatar,
  })
  # return redirect('chef_detail', pk=pk)

def add_booking(request, pk):
  form = BookingForm(request.POST)
  if form.is_valid():
    new_schedule = form.save(commit=False)
    new_schedule.chef_id = pk
    new_schedule.save()
  
  return redirect('chef_detail', pk=pk)


class ChefsCreate(LoginRequiredMixin, CreateView):
  model = Chef
  fields = '__all__'

class ChefsUpdate(LoginRequiredMixin, UpdateView):
  model = Chef
  fields = '__all__'

class ChefsDelete(LoginRequiredMixin, DeleteView):
  model = Chef
  success_url = '/chefs/'

def user_detail(request, pk):
  user = User.objects.get(id=pk)
  return render(request, 'user/detail.html', { 'user': user })

class UserCreate(CreateView):
  model = User
  fields = '__all__'

class UserUpdate(UpdateView):
  model = User
  fields = '__all__'

class UserDelete(DeleteView):
  model = User
  success_url = '/chefs/'

# @login_required
def add_avatar(request, pk):
  # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f'{S3_BASE_URL}{BUCKET}/{key}'
            photo = Avatar(url=url, chef_id=pk)
            photo.save()
        except Exception as error:
            print(f'an error occurred uploading to AWS S3')
            print(error)
    return redirect('chef_detail', pk=pk)

# @login_required
# def add_gallery(request, pk):
  # gallery_files = request.FILES.getlist('photo-file', None)

  # if gallery_files:
  #   s3 = boto3.client('s3')
  #   key = uuid.uuid4().hex[:6] + gallery_files.name[gallery_files.name.rfind('.'):]

  #   try:
  #     s3.upload.fileobj(gallery_files, BUCKET2, key)
  #     url = f'{S3_BASE_URL}{BUCKET}/{key}'
  #     gallery = Gallery(url=url, chef_id=pk)
  #     gallery.save()
  #   except Exception as error:
  #     print(f'an error occurred uploading to AWS S3')
  #     print(error)
    
  #   return redirect('chef_detail', pk=pk)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('chefs')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ChefforHire</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
    <header class="nav-bar-fixed">
      <nav>
        <div class="nav-wrapper black">
          <ul>
            <!-- <li><i style="color: white;" class="fas fa-utensils"></i></li> -->
            <li>
              <a class="left brand-logo" id="brand" href="{% url 'landing' %}"
                >Chef for Hire</a
              >
            </li>
          </ul>
          <ul>
            <li>
              <a href=""></a>
            </li>
          </ul>
          <ul class="right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'chefs' %}">Chefs</a></li>
            <li><a href="{% url 'chef_create' %}">Create Chef Profile</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>

            {% else %}
            <li><a href="{% url 'signup' %}">Chef Sign Up</a></li>
            <li><a href="{% url 'login' %}">Chef Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
    <footer class="page-footer black orange-text darken-3">
      <div class="center">All Rights Reserved, &copy; 2021 Chef for Hire</div>
    </footer>
  </body>
</html>

main_app/templates/chefs/detail.html
{% extends 'base.html' %} {% load static %} {% block content %} {% comment %}
<h1>Chef Profile</h1>
{% endcomment %}
<section class="topsection">
  <div class="showcase">
    <div class="chef-profile">
      <!-- {% comment %} class="col s6" {% endcomment %} -->
      <!-- <img class="chef-img" src="{{photo.url}}" alt="{{ chef.name }}" /> -->

      {% for photo in avatar %}
      <img
        class="responsive-img"
        src="{{ photo.url }}"
        alt="{{chef.name}}"
      /><br />
      {% empty %}
      <div class="card-panel red-text center-align">No Photos</div>
      <br />
      {% endfor %}

      <form
        action="{% url 'add_avatar' chef.id %}"
        enctype="multipart/form-data"
        method="post"
        class="card-panel"
      >
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br /><br />
        <input type="submit" class="btn orange" value="Upload Photo" />
      </form>
    </div>
    <!-- <form
      action="{% url 'add_avatar' chef.id %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <input class="double-break" type="file" name="avatar_file" />

      <input type="submit" value="Upload Photo" />
    </form> -->
    <div class="info-section">
      <div class="detail-card">
        <h5>{{chef.name}}</h5>
        <p>{{chef.email}}</p>
        <p>{{chef.location}}</p>
        <p>${{chef.hourly}} <span>hourly</span></p>
        <p>⭐⭐⭐⭐</p>
        <div class="card-action">
          <a class="btn blue" href="{% url 'chef_update' chef.id %}"
            >Edit Profile</a
          >
          <a class="btn red" href="{% url 'chef_delete' chef.id %}"
            >Delete Profile</a
          >
        </div>
        <br />
        <div class="bio">
          <p>{{chef.bio}}</p>
        </div>
      </div>
      <div class="bookingform">
        <!-- <div class="col s6"> -->
        <div class="mealform">
          <form action="{% url 'add_booking' chef.id %}" method="post">
            {% csrf_token %} {{ booking_form.as_p }}
            <input class="btn orange" type="submit" value="Add Booking" />
          </form>
        </div>

        <div class="tableform">
          <table class="detail-table striped responsive-table">
            <thead>
              <tr>
                <th>Host</th>
                <th>Occassion</th>
                <th>Date</th>
                <th>Attendees</th>
                <th>Meal</th>
              </tr>
            </thead>
            <tbody>
              {% for booking in chef.booking_set.all %}
              <tr>
                <td>{{ booking.host}}</td>
                <td>{{ booking.occassion}}</td>
                <td>{{ booking.date }}</td>
                <td>{{ booking.attendees }}</td>
                <td>{{ booking.get_meal_display }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- </div> -->
      </div>
    </div>
  </div>
</section>
<section>
  <div class="row gallery">
    <div class="col s12">
      <h4 class="menu-gallery">Menu Gallery</h4>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img1.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img2.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img3.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img4.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img5.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
      <div class="col s4">
        <img
          class="menu-img"
          src="{% static 'images/img6.jpg' %}"
          alt="menu"
          class="card responsive-img"
        />
      </div>
    </div>
  </div>
</section>
<section>
  <div class="row">
    <h4 class="testimonial">Testimonials</h4>
    <div class="col s4">
      <!-- Promo Content 1 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam,
        eveniet? Laboriosam molestiae eligendi voluptas maiores distinctio sequi
        aliquid temporibus ducimus.
      </p>
    </div>
    <div class="col s4">
      <!-- Promo Content 2 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur eius,
        aspernatur dolore veniam nobis ipsum enim incidunt. Eaque, expedita
        quisquam.
      </p>
    </div>
    <div class="col s4">
      <!-- Promo Content 3 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum
        voluptates cupiditate nemo perferendis perspiciatis praesentium numquam
        magnam labore. Aliquam, voluptate?
      </p>
    </div>
  </div>
</section>
<script>
  const dateEl = document.getElementById('id_date');
  const selectEl = document.getElementById('id_meal');

  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/chefs/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<h1 class="indexhead">Chef's for Hire</h1>
{% for chef in object_list %}
<div id="chefindex" class="card">
  {% comment %}
  <a href="{% url 'chef_detail' chef.id %}">
    {% endcomment %}
    <div class="card-content">
      <span class="card-title orange-text">{{chef.name}}</span>

      <p>Phone: {{chef.phone}}</p>
      <p>Email: {{chef.email}}</p>
      <p>Bio: {{chef.bio}}</p>
      <p>Location: {{chef.location}}</p>
      <p>Hourly: ${{chef.hourly}}</p>
      <br />
      <a
        id=""
        class="view-profile btn orange"
        href="{% url 'chef_detail' chef.id %}"
        >View Profile</a
      >
    </div>
    {% comment %}
  </a>
  {% endcomment %}
</div>
{% endfor %} {% endblock %}

main_app/templates/landing.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <div class="landing-info">
    <div class="firstbox">
      <!-- <img src="{% static 'images/landingpage.jpeg' %}" alt="chef pic"> -->
    </div>
    <div class="firstbox">
      <h3 class="lpheading">
        Hire a local chef
        <br />
        for any occasion.
      </h3>
      <a class="lp-cta" href="{% url 'chefs' %}">Get Started</a>
    </div>
  </div>

  <div class="landing-about">
    <div class="secondbox"></div>
    <div class="col s6 about-text">
      <h3 class="together">
        Bring family and <br />
        friends together.
      </h3>
    </div>
  </div>
  {% comment %} Chef's CTA {% endcomment %}
  <div class="chef-cta">
    <div class="chef-cta-text">
      <h3>
        Looking to create a memorable dining <br />
        experience for clients in your area?
      </h3>
      <a href="{% url 'chef_create' %}" class="lp-apply">Apply Now</a>
    </div>
  </div>

  {% comment %}
  <h4>Testimonials</h4>
  <p>See what others have said about Chef for Hire.</p>
  <div class="row">
    <div class="col s4">
      <!-- Promo Content 1 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam,
        eveniet? Laboriosam molestiae eligendi voluptas maiores distinctio sequi
        aliquid temporibus ducimus.
      </p>
    </div>
    <div class="col s4">
      <!-- Promo Content 2 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur eius,
        aspernatur dolore veniam nobis ipsum enim incidunt. Eaque, expedita
        quisquam.
      </p>
    </div>
    <div class="col s4">
      <!-- Promo Content 3 goes here -->
      <h6>Test</h6>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum
        voluptates cupiditate nemo perferendis perspiciatis praesentium numquam
        magnam labore. Aliquam, voluptate?
      </p>
    </div>
  </div>
  {% endcomment %}
</div>

{% endblock %}

main_app/templates/main_app/chef_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Chef Profile</h1>

<h4>
  Are you sure you want to delete
  <span class="red-text">{{object.name}}</span>
</h4>

<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete" class="btn red" />
  <a href="{% url 'chef_detail' object.id %}" class="btn blue">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/chef_form.html
{% extends 'base.html' %}

{% block content %}

<div id="chefcreate" class="card card-content blue-text">

{% if object %}
    <h1>Update {{ object.name }}'s Information</h1>
{% else %}
    <h1>Private Chef Sign Up</h1>  
{% endif %}

<form action="" method="post">
{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="{% if object %} Update Chef {% else %} Add New Chef {% endif %}">

</form>
</div>
{% endblock %}